#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Audit All Franchisee Repositories
# ============================================================================
# Generates a compliance audit report across all franchisee repos.
#
# Usage: ./audit-repos.sh [--output report.md]
# ============================================================================

MASTER_ORG="Light-Brands"
DATE=$(date +%Y-%m-%d)
OUTPUT="audit-report-${DATE}.md"

while [[ $# -gt 0 ]]; do
  case $1 in
    --output) OUTPUT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

echo "================================================"
echo "Living Light OS — Network Audit"
echo "Date: $DATE"
echo "================================================"

# Get all franchisee repos
echo "Finding all franchisee repositories..."
mapfile -t REPOS < <(gh repo list "$MASTER_ORG" \
  --json name,updatedAt,visibility \
  --jq '.[] | select(.name | startswith("living-light-church-")) | .name')

TOTAL=${#REPOS[@]}
echo "Found $TOTAL franchisee repos"
echo ""

# Start report
cat > "$OUTPUT" << EOF
# Living Light OS — Network Audit Report

**Date:** $DATE
**Total Franchisees:** $TOTAL

---

## Franchisee Status

| Church | Last Updated | Compliance Workflow | Open Issues | Status |
|--------|-------------|-------------------|-------------|--------|
EOF

HEALTHY=0
WARNING=0
CRITICAL=0

for repo in "${REPOS[@]}"; do
  FULL_REPO="$MASTER_ORG/$repo"
  CHURCH_NAME=$(echo "$repo" | sed 's/living-light-church-//;s/-/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2)}1')

  # Get last update
  UPDATED=$(gh repo view "$FULL_REPO" --json updatedAt --jq '.updatedAt' 2>/dev/null | cut -d'T' -f1)

  # Check workflow runs
  LAST_RUN=$(gh run list --repo "$FULL_REPO" --workflow "Compliance Check" --limit 1 --json conclusion --jq '.[0].conclusion' 2>/dev/null || echo "none")

  # Count open issues
  ISSUES=$(gh issue list --repo "$FULL_REPO" --label "compliance" --state open --json number --jq 'length' 2>/dev/null || echo "0")

  # Determine status
  if [ "$LAST_RUN" = "failure" ] || [ "$ISSUES" -gt 3 ]; then
    STATUS="CRITICAL"
    CRITICAL=$((CRITICAL + 1))
  elif [ "$LAST_RUN" = "none" ] || [ "$ISSUES" -gt 0 ]; then
    STATUS="WARNING"
    WARNING=$((WARNING + 1))
  else
    STATUS="HEALTHY"
    HEALTHY=$((HEALTHY + 1))
  fi

  echo "| $CHURCH_NAME | $UPDATED | $LAST_RUN | $ISSUES | $STATUS |" >> "$OUTPUT"
  echo "  $repo: $STATUS (issues: $ISSUES, workflow: $LAST_RUN)"
done

# Summary
cat >> "$OUTPUT" << EOF

---

## Summary

| Status | Count |
|--------|-------|
| Healthy | $HEALTHY |
| Warning | $WARNING |
| Critical | $CRITICAL |
| **Total** | **$TOTAL** |

---

*Generated by Living Light OS Audit Tool — $DATE*
EOF

echo ""
echo "================================================"
echo "Audit Complete"
echo "  Healthy:  $HEALTHY"
echo "  Warning:  $WARNING"
echo "  Critical: $CRITICAL"
echo "================================================"
echo ""
echo "Report saved to: $OUTPUT"
